nome = input("Digite o nome: ")
cpf = input("Digite o cpf:")
rg = input("Digite o rg:")
dataNascimento = input("Digite a data de nascimento:")
sexo = input("Digite o sexo da pessoa: ")
peso = float(input("Digite o nome o peso: "))
tipoSanguineo = input("Digite o tipo sanguineo: ")
renda = float(input("Digite a renda do usuario:"))
endereco = input(input("Digite o Endereco: "))
telefone = input(input("Digite o Telefone: "))
cidade = input("Digite a cidade: ")
Estado = input("Digite o Estado")


print("+------------------------------+")
print("|          Informações           ")
print("|Nome: ", nome)
print("|Cpf:  ", cpf)
print("|Rg:   ", rg)
print("|Data de Nascimento", dataNascimento)
print("|Sexo: ", sexo)
print("|Peso: ", peso)
print("|Tipo Sanguineo:", tipoSanguineo)
print("|Renda: ", renda)
print("Endereco: ",endereco)
print("Telefone", telefone)
print("Cidade: ", cidade)
print("Estado: ", Estado)